channels:
- conda-forge
- defaults
dependencies:
- python=3.11
- pip:
  - annotated-types==0.7.0
  - appnope==0.1.4
  - asttokens==3.0.1
  - beautifulsoup4==4.13.4
  - choreographer==1.2.1
  - click==8.1.8
  - comm==0.2.3
  - debugpy==1.8.20
  - decorator==5.2.1
  - executing==2.2.1
  - feather-format==0.4.1
  - fire==0.7.1
  - iniconfig==2.3.0
  - ipykernel==6.30.1
  - ipython==9.10.0
  - ipython-pygments-lexers==1.1.1
  - jedi==0.19.2
  - jinja2==3.1.6
  - joblib==1.5.3
  - jupyter-client==8.8.0
  - jupyter-core==5.9.1
  - kaleido==1.2.0
  - logistro==2.0.1
  - loguru==0.7.3
  - markupsafe==3.0.3
  - matplotlib-inline==0.2.1
  - narwhals==2.16.0
  - nest-asyncio==1.6.0
  - numpy==2.4.2
  - orjson==3.11.7
  - pandas==2.3.1
  - parso==0.8.5
  - pexpect==4.9.0
  - platformdirs==4.5.1
  - plotly==6.5.2
  - pluggy==1.6.0
  - prompt-toolkit==3.0.52
  - psutil==7.2.2
  - ptyprocess==0.7.0
  - pure-eval==0.2.3
  - pyarrow==23.0.0
  - pydantic==2.12.5
  - pydantic-core==2.41.5
  - pygments==2.19.2
  - pytest==9.0.2
  - pytest-timeout==2.4.0
  - python-dateutil==2.9.0.post0
  - python-dotenv==1.1.1
  - pytz==2025.2
  - pyyaml==6.0.2
  - pyzmq==27.1.0
  - scikit-learn==1.5.2
  - scipy==1.17.0
  - simplejson==3.20.2
  - six==1.17.0
  - soupsieve==2.8.3
  - stack-data==0.6.3
  - termcolor==3.3.0
  - threadpoolctl==3.6.0
  - tornado==6.5.4
  - traitlets==5.14.3
  - typing-extensions==4.15.0
  - typing-inspection==0.4.2
  - tzdata==2025.3
  - wcwidth==0.5.3
prefix: /opt/anaconda3/envs/ml-algo-scratch